import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Tokens } from 'next-firebase-auth-edge/lib/auth';
import { UserInfo } from 'firebase/auth';
import AuthSession from '../components/AuthSession';
import { Roboto } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Buddies',
  description: 'Generated by create next app',
};

// RootLayout
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${inter.className} ${roboto.variable}`}>
      <head></head>
      <body >
        <AuthSession>{children}</AuthSession>
      </body>
    </html>
  );
}
